function items(...pairs: Array<[string, string]>) {
  return pairs.map(([word, meaning]) => ({ word, meaning }));
}

export const BEGINNER_BANK = items(
  ["cat", "貓"],
  ["dog", "狗"],
  ["sun", "太陽"],
  ["book", "書"],
  ["tree", "樹"],
  ["water", "水"],
  ["happy", "快樂的"],
  ["friend", "朋友"],
  ["school", "學校"],
  ["apple", "蘋果"],
  ["house", "房子"],
  ["light", "光"],
  ["music", "音樂"],
  ["green", "綠色的"],
  ["table", "桌子"],
  ["chair", "椅子"],
  ["phone", "電話"],
  ["window", "窗戶"],
  ["paper", "紙"],
  ["river", "河"],
  ["cloud", "雲"],
  ["smile", "微笑"],
  ["bread", "麵包"],
  ["sleep", "睡覺"],
  ["winter", "冬天"],
  ["family", "家人"],
  ["bird", "鳥"],
  ["fish", "魚"],
  ["milk", "牛奶"],
  ["rain", "雨"],
  ["star", "星星"],
  ["moon", "月亮"],
  ["hand", "手"],
  ["foot", "腳"],
  ["blue", "藍色的"],
  ["red", "紅色的"],
  ["ball", "球"],
  ["door", "門"],
  ["room", "房間"],
  ["food", "食物"],
  ["cake", "蛋糕"],
  ["park", "公園"],
  ["game", "遊戲"],
  ["time", "時間"],
  ["home", "家"],
  ["love", "愛"],
  ["good", "好的"],
  ["small", "小的"],
  ["big", "大的"],
  ["hot", "熱的"],
  ["cold", "冷的"],
  ["day", "白天"],
  ["night", "夜晚"],
  ["year", "年"],
  ["week", "週"],
  ["city", "城市"],
  ["road", "路"],
  ["car", "汽車"],
  ["bus", "公車"],
  ["train", "火車"],
  ["shop", "商店"],
  ["bag", "袋子"],
  ["pen", "筆"],
  ["desk", "書桌"],
  ["class", "班級"],
  ["teacher", "老師"],
  ["student", "學生"],
  ["name", "名字"],
  ["hello", "你好"],
  ["please", "請"],
  ["thanks", "謝謝"],
  ["yes", "是"],
  ["no", "不是"],
  ["open", "打開"],
  ["close", "關閉"],
  ["walk", "走路"],
  ["run", "跑"],
  ["jump", "跳"],
  ["eat", "吃"],
  ["drink", "喝"]
);

export const ADVANCED_BANK = items(
  ["because", "因為"],
  ["together", "一起"],
  ["important", "重要的"],
  ["beautiful", "美麗的"],
  ["language", "語言"],
  ["computer", "電腦"],
  ["morning", "早上"],
  ["weather", "天氣"],
  ["journey", "旅程"],
  ["practice", "練習"],
  ["mountain", "山"],
  ["library", "圖書館"],
  ["question", "問題"],
  ["elephant", "大象"],
  ["birthday", "生日"],
  ["kitchen", "廚房"],
  ["rainbow", "彩虹"],
  ["holiday", "假日"],
  ["umbrella", "雨傘"],
  ["chocolate", "巧克力"],
  ["adventure", "冒險"],
  ["calendar", "日曆"],
  ["sandwich", "三明治"],
  ["treasure", "寶藏"],
  ["tomorrow", "明天"],
  ["yesterday", "昨天"],
  ["afternoon", "下午"],
  ["evening", "傍晚"],
  ["breakfast", "早餐"],
  ["vegetable", "蔬菜"],
  ["hospital", "醫院"],
  ["airplane", "飛機"],
  ["station", "車站"],
  ["direction", "方向"],
  ["remember", "記得"],
  ["forget", "忘記"],
  ["understand", "理解"],
  ["explain", "解釋"],
  ["decide", "決定"],
  ["problem", "問題"],
  ["answer", "答案"],
  ["example", "例子"],
  ["sentence", "句子"],
  ["dictionary", "字典"],
  ["homework", "回家作業"],
  ["classroom", "教室"],
  ["notebook", "筆記本"],
  ["backpack", "背包"],
  ["weekend", "週末"],
  ["vacation", "假期"],
  ["festival", "節慶"],
  ["present", "禮物"],
  ["surprise", "驚喜"],
  ["favorite", "最喜歡的"],
  ["different", "不同的"],
  ["possible", "可能的"],
  ["necessary", "必要的"],
  ["dangerous", "危險的"],
  ["careful", "小心的"],
  ["friendly", "友善的"],
  ["polite", "有禮貌的"],
  ["quietly", "安靜地"],
  ["quickly", "快速地"],
  ["already", "已經"],
  ["usually", "通常"],
  ["sometimes", "有時候"],
  ["always", "總是"],
  ["never", "從不"],
  ["perhaps", "也許"],
  ["however", "然而"],
  ["although", "雖然"],
  ["between", "在……之間"],
  ["without", "沒有"],
  ["through", "穿過"],
  ["around", "在附近"],
  ["enough", "足夠的"],
  ["several", "幾個"],
  ["special", "特別的"],
  ["complete", "完整的"],
  ["continue", "繼續"]
);

export const PHRASE_BANK = items(
  ["good morning", "早安"],
  ["thank you", "謝謝"],
  ["see you later", "待會見"],
  ["how are you", "你好嗎"],
  ["nice to meet you", "很高興認識你"],
  ["have a nice day", "祝你有美好的一天"],
  ["what time is it", "現在幾點"],
  ["I am hungry", "我餓了"],
  ["lets go home", "我們回家吧"],
  ["wait a minute", "等一下"],
  ["of course", "當然"],
  ["after school", "放學後"],
  ["on the weekend", "在週末"],
  ["take a break", "休息一下"],
  ["look at this", "看看這個"],
  ["once upon a time", "從前從前"],
  ["in the afternoon", "在下午"],
  ["a cup of tea", "一杯茶"],
  ["my best friend", "我最好的朋友"],
  ["practice makes perfect", "熟能生巧"],
  ["keep it up", "繼續保持"],
  ["well done", "做得好"],
  ["never give up", "永不放棄"],
  ["piece of cake", "輕而易舉"],
  ["break a leg", "祝你好運"],
  ["see you soon", "很快再見"],
  ["good night", "晚安"],
  ["excuse me", "對不起／借過"],
  ["I am sorry", "我很抱歉"],
  ["you are welcome", "不客氣"],
  ["no problem", "沒問題"],
  ["take care", "保重"],
  ["come on in", "請進"],
  ["sit down please", "請坐下"],
  ["how much is it", "這個多少錢"],
  ["I like it", "我喜歡它"],
  ["I dont know", "我不知道"],
  ["can you help me", "你可以幫我嗎"],
  ["where is the station", "車站在哪裡"],
  ["I am ready", "我準備好了"],
  ["lets start now", "我們現在開始吧"],
  ["wait for me", "等我一下"],
  ["hurry up", "快一點"],
  ["slow down", "慢一點"],
  ["be careful", "小心"],
  ["good luck", "祝你好運"],
  ["long time no see", "好久不見"],
  ["what do you think", "你覺得怎麼樣"],
  ["I think so", "我也這麼認為"],
  ["me too", "我也是"],
  ["not yet", "還沒"],
  ["just a moment", "稍等一下"],
  ["over there", "在那邊"],
  ["right here", "就在這裡"],
  ["on the left", "在左邊"],
  ["on the right", "在右邊"],
  ["next to me", "在我旁邊"],
  ["in the morning", "在早上"],
  ["at night", "在晚上"],
  ["for a while", "一會兒"],
  ["by the way", "對了／順便一提"],
  ["as soon as possible", "盡快"],
  ["make a wish", "許一個願"],
  ["take a seat", "請坐"],
  ["give me a hand", "幫我一下"],
  ["hold on please", "請稍候"],
  ["lets try again", "我們再試一次"],
  ["I got it", "我懂了"],
  ["that sounds good", "聽起來不錯"],
  ["see you tomorrow", "明天見"]
);

export const CHALLENGE_BANK = items(
  ["apple", "蘋果"],
  ["beautiful", "美麗的"],
  ["take care", "保重"],
  ["chocolate", "巧克力"],
  ["good morning", "早安"],
  ["never give up", "永不放棄"],
  ["treasure", "寶藏"],
  ["see you soon", "很快再見"],
  ["umbrella", "雨傘"],
  ["well done", "做得好"],
  ["adventure", "冒險"],
  ["thank you", "謝謝"],
  ["rainbow", "彩虹"],
  ["keep it up", "繼續保持"],
  ["language", "語言"],
  ["of course", "當然"],
  ["calendar", "日曆"],
  ["wait a minute", "等一下"],
  ["journey", "旅程"],
  ["piece of cake", "輕而易舉"],
  ["computer", "電腦"],
  ["take a break", "休息一下"],
  ["elephant", "大象"],
  ["break a leg", "祝你好運"],
  ["hello", "你好"],
  ["please", "請"],
  ["family", "家人"],
  ["window", "窗戶"],
  ["school", "學校"],
  ["friend", "朋友"],
  ["morning", "早上"],
  ["weather", "天氣"],
  ["kitchen", "廚房"],
  ["holiday", "假日"],
  ["station", "車站"],
  ["problem", "問題"],
  ["answer", "答案"],
  ["quickly", "快速地"],
  ["enough", "足夠的"],
  ["special", "特別的"],
  ["good luck", "祝你好運"],
  ["no problem", "沒問題"],
  ["hurry up", "快一點"],
  ["be careful", "小心"],
  ["I got it", "我懂了"],
  ["me too", "我也是"],
  ["not yet", "還沒"],
  ["over there", "在那邊"],
  ["right here", "就在這裡"],
  ["excuse me", "對不起／借過"],
  ["come on", "加油／來吧"],
  ["lets go", "我們走吧"],
  ["hold on", "等一下"],
  ["sit down", "坐下"],
  ["stand up", "站起來"],
  ["look out", "當心"],
  ["come back", "回來"],
  ["try again", "再試一次"],
  ["all right", "好的"],
  ["for sure", "當然"],
  ["next time", "下次"],
  ["this way", "這邊走"],
  ["that way", "那邊走"],
  ["too late", "太遲了"],
  ["too easy", "太簡單了"],
  ["very good", "非常好"],
  ["so close", "好接近"],
  ["nice job", "做得好"],
  ["great work", "幹得好"],
  ["ready go", "預備開始"],
  ["time out", "暫停"],
  ["game on", "開始比賽"],
  ["high five", "擊掌"],
  ["open up", "打開"],
  ["close it", "關掉它"]
);
